### ISSUE TITLE
Potential request spamming after initial cooldown surpassed

### ISSUE THREAD

**Issue by earloc** [Azure/AppConfiguration-JavaScriptProvider#137]
Hey Folks.

We recently had a situation in one of our environments, where usage of the `refresh`-api somehow overwhelmed our `azconfig` instances, which then gave HTTP `429 Too-many-requests`, occasionally - especially during peak-load times of our app.

We used [1.0.0-preview4](https://github.com/Azure/AppConfiguration-JavaScriptProvider/releases/tag/1.0.0-preview.4) at this time and thx to @lorenzadomat found out, that the refresh-interval might be ignored, somehow.

I then took the opportunity to narrow this even further down. Seems like starting with [1.1.0](https://github.com/Azure/AppConfiguration-JavaScriptProvider/releases/tag/1.1.0) / [b1cf8099fbf8737de3d38299be2871d4547c7cac ](https://github.com/Azure/AppConfiguration-JavaScriptProvider/pull/65/commits/b1cf8099fbf8737de3d38299be2871d4547c7cac), this behavior dissappeared.

Looks like prior 1.1.0, sentinel keys got queried every time, after the initial `refreshIntervalInMs` has been surpassed - before this has happened, everything works as expected - that's why this was not that easy to reproduce ;)

Just wanted to let you know about this, especially as this might have been fixed "by accident" and not on purpose.

I have a simple repro over at my [repro-repo](https://github.com/earloc/repros/tree/main/src/azure/AppConfiguration-JavaScriptProvider#httpsgithubcomazureappconfiguration-javascriptproviderissues137), which hopefully showcases the problem clear enough.

Let me know if this somehow might help in preventing some future regressions. We will probably notice, at least.

**Comment by lorenzadomat** [comment]
I guess this is related to this [comment](https://github.com/Azure/AppConfiguration-JavaScriptProvider/pull/65#discussion_r1694289732)

**Comment by zhiyuanliang-ms** [comment]
Hi, @earloc Thank you for reaching out! I also released this issue. Could you check this PR #136. Did the code snippet in the description illustrate the problem you met?

**Comment by earloc** [comment]
@zhiyuanliang-ms No, the scenario you outlined in #136 seems to be different, as it only strikes when callers may not actually `await` the `refresh()` (which we do) - and therfore falling into an even more tighter problematic scenario with macro / micro-tasks. 
[![Image](https://github.com/user-attachments/assets/6f777cdf-6223-49fd-ab8a-f90b26944cb5)](https://medium.com/@lydiahallie/javascript-visualized-promises-async-await-a3f1aad8a943)

As @lorenzadomat  suggested, the fix for us was probably a side-effect of this [comment](https://github.com/Azure/AppConfiguration-JavaScriptProvider/pull/65#discussion_r1694289732), as the internal timer was not reset when there where no changes to the watched sentinel-keys. The fix you suggest over at #136 wouldn't prevent our scenario (which doesn't happen with 1.1.0 forward). But it might have an effect on others, which are not `await`ing - not sure if a library is responsible for preventing such bad callers, though ;).

**Comment by zhiyuanliang-ms** [comment]
@earloc Oh, I see. I didn't notice that you await the refresh call. Taking a look at it.

**Comment by earloc** [comment]
@zhiyuanliang-ms just to make sure: Our problem disappeared with 1.1.0. But as there was no issue about this, I just wanted to document it here (and maybe higher the chance that this won't accidently get re-introduced in future Version).

I might have a look into providing a unit-test similar to the one I used in my repro to guard against this - when I find the time 😇).

Heads up, and thx for coming back on this so fast 💪.

**Comment by zhiyuanliang-ms** [comment]
@earloc Big thanks! 😃 Glad to hear that using 1.1.0 can solve your problem. I will add more testcase in this repo to guard against it. I will close this issue now.
