### ISSUE TITLE
Feature Flags explicitly excluded?

### ISSUE THREAD

**Issue by earloc** [Azure/AppConfiguration-JavaScriptProvider#62]
Hi.

Is there a particular reason why feature-flags are [explicitly excluded](https://github.com/Azure/AppConfiguration-JavaScriptProvider/blob/5bcc6b9a7efad885fdeaa2cf84cf6ad428218ff7/src/AzureAppConfigurationImpl.ts#L152C13-L156C14)?

Trying to get hands on integrating with feature-flags and now stumbling over this.

Probably will end up using [@azure/app-configuration](https://www.npmjs.com/package/@azure/app-configuration), yet still wondering why we are not able to maybe at least opt-in to include feature-flags as well

**Comment by Eskibear** [comment]
> Trying to get hands on integrating with feature-flags and now stumbling over this

Yes, that's the trade-off. But we don't want to create future breaking changes if possible, as described in #55 

Repo for feature management: https://github.com/microsoft/FeatureManagement-JavaScript
We will release a preview version soon. For the moment, probably you can checkout the repo and build the tgz package locally and give it a try. Please let us know the early feedback!
