### ISSUE TITLE
Support listing by etags

### ISSUE THREAD

**Issue by Eskibear** [Azure/AppConfiguration-JavaScriptProvider#67]
Did JS SDK release collection monitoring API? I see they had a PR for this but not sure if this exists in the latest stable release: https://github.com/Azure/azure-sdk-for-js/pull/28555

_Originally posted by @avanigupta in https://github.com/Azure/AppConfiguration-JavaScriptProvider/pull/65#discussion_r1626646203_
            

SDK v1.6.0 includes the new API listing by page etags. We might adopt that in refreshing both key-values and feature flags.

**Comment by Eskibear** [comment]
feature flags are refreshed based on page etags in #65

**Comment by Eskibear** [comment]
For key-value refreshing, the behavior is related to `watchedSettings`

Current behavior when `watchedSettings` is 
- **undefined**: Error
- **empty list**: Error  <--- // To be enhanced
- **non-empty list**: sentinel-based refresh.

With the pageEtag based listing API. Now we are able to impl refresh without requiring a sentinel key (watched setting). The proposal is, when `watchedSettings` is an empty list, it indicates we don't watch any specific setting, but use page Etags to determine whether to refresh or not.

**Comment by zhiyuanliang-ms** [comment]
#133
